"""Generate a volume mesh suitable for CFD from a vessel surface.

This is VMTK's vmtkmeshgenerator script as a Slicer module. The script itself cannot be run here:
it drives the pipeline through the `vmtk` Python package, which the Slicer extension does not
install - only the wrapped C++ classes are available. The pipeline is the same one, built out of
those classes directly, in CfdMeshGeneratorLib.MeshingPipeline, and every parameter the script
exposes is exposed here under the same name, meaning and default - bar the few a dialog reads
better asking the other way round: a surface is asked to be capped and remeshed rather than to
have capping and remeshing skipped, and an edge length limit of 0 is the script's "no limit".

Apply does not run the pipeline in the application. It hands the surface and the parameters to
CfdMeshGeneratorLib.MeshingWorker, running in a PythonSlicer of its own, and reads the mesh back
from it: a run can then be cancelled, and a mesher that crashes takes that process rather than
this one. It is also what lets fTetWild be run in a Python other than Slicer's where Slicer's
cannot host it (see CfdMeshGeneratorLib.FTetWild).
"""

import collections
import json
import logging
import os
import queue
import shutil
import signal
import subprocess
import sys
import threading
import time
from typing import Annotated

import qt
import vtk

import slicer
from slicer.i18n import tr as _
from slicer.i18n import translate
from slicer.ScriptedLoadableModule import *
from slicer.util import VTKObservationMixin
from slicer.parameterNodeWrapper import parameterNodeWrapper, Minimum

from slicer import vtkMRMLModelNode

from CfdMeshGeneratorLib import FTetWild, MeshingWorker
from CfdMeshGeneratorLib.MeshingPipeline import (  # noqa: F401 - re-exported for scripts and tests
    DEFAULT_BOUNDARY_LABELS_ARRAY_NAME, DEFAULT_BOUNDARY_POINT_ORDER_ARRAY_NAME,
    DEFAULT_CAP_IDS_ARRAY_NAME,
    FTETWILD_REQUIREMENT, MINIMUM_SUBSTEPS, UNLIMITED_EDGE_LENGTH,
    CappingMethod, ElementSizeMode, Mesher, MeshingPipeline, VolumeMeshing)


class MeshingCancelledError(Exception):
    """A run was stopped by cancel() before it finished. Not an error to show a dialog for: it
    is what was asked for."""


#
# CfdMeshGenerator
#


class CfdMeshGenerator(ScriptedLoadableModule):
    """Uses ScriptedLoadableModule base class, available at:
    https://github.com/Slicer/Slicer/blob/main/Base/Python/slicer/ScriptedLoadableModule.py
    """

    def __init__(self, parent):
        ScriptedLoadableModule.__init__(self, parent)
        self.parent.title = _("CFD Mesh Generator")
        self.parent.categories = [translate("qSlicerAbstractCoreModule", "Vascular Modeling Toolkit")]
        self.parent.dependencies = []
        self.parent.contributors = ["Luca Antiga (Orobix)", "David Steinman (University of Toronto)"]
        self.parent.helpText = _("""
Fill a vessel surface with tetrahedra, ready for a computational fluid dynamics solver. The
surface is capped, remeshed into near equilateral triangles, optionally lined on the inside with a
prismatic boundary layer, and filled by TetGen or fTetWild. Every cell of the result carries the id of the
face it belongs to - the wall, or one cap per vessel end - so that a boundary condition can be
assigned per face.
This is the pipeline of VMTK's vmtkmeshgenerator script, with the same parameters.
Documentation is available <a href="https://github.com/vmtk/SlicerExtension-VMTK/blob/master/Docs/CfdMeshGenerator.md">here</a>.
""")
        self.parent.acknowledgementText = _("""
This module wraps the mesh generation pipeline of the Vascular Modeling Toolkit (www.vmtk.org),
developed by Luca Antiga and David Steinman.
The volume mesh is generated by TetGen, by Hang Si, or by fTetWild.
TetGen is licensed under the terms of the MIT license with exceptions, one of which is that
distribution of it for any commercial purpose is permissible only by direct arrangement with the
copyright owner. For private, research and educational purposes it can be used at no cost and
without further arrangements. Anyone putting this module to commercial use should read TetGen's
license first.
fTetWild is "Fast Tetrahedral Meshing in the Wild", by Yixin Hu, Teseo Schneider, Bolun Wang,
Denis Zorin and Daniele Panozzo (ACM Transactions on Graphics 39(4), SIGGRAPH 2020), under the
Mozilla Public License 2.0. It is used through the pytetwild package of the PyVista project,
which the module downloads from PyPI the first time fTetWild is asked for.
""")


#
# CfdMeshGeneratorParameterNode
#


@parameterNodeWrapper
class CfdMeshGeneratorParameterNode:
    """The parameters of the meshing pipeline, stored in the scene.

    inputSurface - the surface to fill with tetrahedra; its open boundaries are capped first
    outputMesh - model node the volume mesh is written into
    outputRemeshedSurface - optional model node the remeshed surface alone is written into

    The rest are the parameters of vmtkmeshgenerator, described one by one on
    CfdMeshGeneratorLogic.generateMesh(), which keeps the names and the senses the script uses:
    capSurface, remeshSurface and remeshWall here are its skipCapping, skipRemeshing and
    remeshCapsOnly negated.
    """

    inputSurface: vtkMRMLModelNode
    outputMesh: vtkMRMLModelNode
    outputRemeshedSurface: vtkMRMLModelNode

    # Surface mesh
    elementSizeMode: ElementSizeMode = ElementSizeMode.EDGE_LENGTH
    targetEdgeLength: Annotated[float, Minimum(0.0)] = 1.0
    targetEdgeLengthArrayName: str = ""
    targetEdgeLengthFactor: Annotated[float, Minimum(0.0)] = 1.0
    maxEdgeLength: Annotated[float, Minimum(0.0)] = 0.0
    minEdgeLength: Annotated[float, Minimum(0.0)] = 0.0
    triangleSplitFactor: Annotated[float, Minimum(0.0)] = 5.0
    remeshSurface: bool = True
    remeshWall: bool = True

    # Capping
    capSurface: bool = True
    cappingMethod: CappingMethod = CappingMethod.SIMPLE

    # Volume mesh
    mesher: Mesher = Mesher.TETGEN
    volumeElementScaleFactor: Annotated[float, Minimum(0.0)] = 0.8
    surfaceTolerance: Annotated[float, Minimum(0.0)] = 0.0
    stopEnergy: Annotated[float, Minimum(3.0)] = 10.0
    maxOptimizationPasses: Annotated[int, Minimum(1)] = 80
    coarsen: bool = False
    tetrahedralize: bool = False
    # The names the face ids may be under, comma-separated; the first one the input surface
    # carries is used, and the first of all of them if it carries none. VMTK's own name and the
    # one SimVascular reads the faces of a model by, so that a surface from either is read as
    # labelled without the name being typed in (see MeshingPipeline.chooseCellEntityIdsArrayName).
    cellEntityIdsArrayNames: str = "CellEntityIds, ModelFaceID"
    # Cell array saying which cells are caps, 1 or more on a cap. Where the input carries it,
    # the caps are the faces it marks and the wall may be in any number of faces; where it does
    # not, the wall is face 1 and every face above it is a cap (see MeshingPipeline.isCapId).
    capIdsArrayName: str = DEFAULT_CAP_IDS_ARRAY_NAME
    boundaryLabelsArrayName: str = DEFAULT_BOUNDARY_LABELS_ARRAY_NAME
    boundaryPointOrderArrayName: str = DEFAULT_BOUNDARY_POINT_ORDER_ARRAY_NAME
    # Cell arrays of the input surface to carry onto the faces of the output, comma-separated;
    # see MeshingPipeline.carryCellArrays().
    carriedCellArrays: str = ""

    # Boundary layer
    boundaryLayer: bool = False
    boundaryLayerOnCaps: bool = False
    numberOfSubLayers: Annotated[int, Minimum(0)] = 2
    subLayerRatio: Annotated[float, Minimum(0.0)] = 0.5
    boundaryLayerThicknessFactor: Annotated[float, Minimum(0.0)] = 0.25
    endcapsEdgeLengthFactor: Annotated[float, Minimum(0.0)] = 1.0
    numberOfSubsteps: Annotated[int, Minimum(MINIMUM_SUBSTEPS)] = 2000
    relaxation: Annotated[float, Minimum(0.0)] = 0.01
    localCorrectionFactor: Annotated[float, Minimum(0.0)] = 0.45


#
# CfdMeshGeneratorWidget
#


class CfdMeshGeneratorWidget(ScriptedLoadableModuleWidget, VTKObservationMixin):
    """Uses ScriptedLoadableModuleWidget base class, available at:
    https://github.com/Slicer/Slicer/blob/main/Base/Python/slicer/ScriptedLoadableModule.py
    """

    def __init__(self, parent=None) -> None:
        """Called when the user opens the module the first time and the widget is initialized."""
        ScriptedLoadableModuleWidget.__init__(self, parent)
        VTKObservationMixin.__init__(self)  # needed for parameter node observation
        self.logic = None
        self._parameterNode = None
        self._parameterNodeGuiTag = None
        # The input surface the outputs are currently named after, so that picking another one
        # is told apart from any other change to the parameter node (see _followInputSurface),
        # and the node itself while it is watched for a surface arriving in it.
        self._followedInputSurfaceId = None
        self._observedInputSurfaceNode = None

    def setup(self) -> None:
        """Called when the user opens the module the first time and the widget is initialized."""
        ScriptedLoadableModuleWidget.setup(self)

        # Load widget from .ui file (created by Qt Designer).
        uiWidget = slicer.util.loadUI(self.resourcePath("UI/CfdMeshGenerator.ui"))
        self.layout.addWidget(uiWidget)
        self.ui = slicer.util.childWidgetVariables(uiWidget)

        # Set scene in MRML widgets. Make sure that in Qt designer the top-level qMRMLWidget's
        # "mrmlSceneChanged(vtkMRMLScene*)" signal is connected to each MRML widget's
        # "setMRMLScene(vtkMRMLScene*)" slot.
        uiWidget.setMRMLScene(slicer.mrmlScene)

        self.logic = CfdMeshGeneratorLogic()

        # These connections ensure that we update the parameter node when the scene is closed
        self.addObserver(slicer.mrmlScene, slicer.mrmlScene.StartCloseEvent, self.onSceneStartClose)
        self.addObserver(slicer.mrmlScene, slicer.mrmlScene.EndCloseEvent, self.onSceneEndClose)

        # Until a surface is picked to name them after (see _followInputSurface), so that a node
        # created from the selector is at least called what it is.
        self.ui.outputMeshSelector.baseName = _("volumetric mesh")
        self.ui.outputRemeshedSurfaceSelector.baseName = _("remeshed surface")

        # A show/hide and an edges button beside each node selector. Neither carries a checked
        # state: it would be saying what the display node holds, and nothing tells it when that
        # changes elsewhere, so the mark would sooner or later contradict the scene. Each reads
        # the state at the moment it is pressed and turns it around.
        self.visibilityButtons = [
            (self.ui.inputSurfaceVisibilityButton, self.ui.inputSurfaceEdgesButton, "inputSurface"),
            (self.ui.outputMeshVisibilityButton, self.ui.outputMeshEdgesButton, "outputMesh"),
            (self.ui.outputRemeshedSurfaceVisibilityButton, self.ui.outputRemeshedSurfaceEdgesButton,
             "outputRemeshedSurface"),
        ]
        # A tool button asks for a taller box than the selector beside it - it sizes itself around
        # its icon - so the row would come out ragged. The height to keep is the selector's, and
        # the icons are scaled to what is left inside once the frame has taken its share. Asked of
        # the widgets rather than written down as a number, so that it stays right whatever the
        # font size, the style and the screen make of them.
        rowHeight = self.ui.inputSurfaceSelector.sizeHint.height()
        for visibilityButton, edgesButton, nodeName in self.visibilityButtons:
            visibilityButton.setIcon(qt.QIcon(":/Icons/Medium/SlicerVisibleInvisible.png"))
            edgesButton.setIcon(qt.QIcon(self.resourcePath("Icons/ToggleEdges.svg")))
            for button in (edgesButton, visibilityButton):
                button.setAutoRaise(True)
                button.setFixedHeight(rowHeight)
                button.setIconSize(qt.QSize(rowHeight - 8, rowHeight - 8))
            visibilityButton.connect("clicked()",
                                     lambda nodeName=nodeName: self.onToggleVisibility(nodeName))
            edgesButton.connect("clicked()",
                                lambda nodeName=nodeName: self.onToggleEdgeVisibility(nodeName))

        # The volume mesh has one more: what is worth looking at in it is inside it.
        self.ui.outputMeshClipButton.setIcon(qt.QIcon(self.resourcePath("Icons/ToggleClipping.svg")))
        self.ui.outputMeshClipButton.setAutoRaise(True)
        self.ui.outputMeshClipButton.setFixedHeight(rowHeight)
        self.ui.outputMeshClipButton.setIconSize(qt.QSize(rowHeight - 8, rowHeight - 8))
        self.ui.outputMeshClipButton.connect("clicked()", self.onToggleClipping)

        self.ui.applyButton.connect("clicked(bool)", self.onApplyButton)

        # What the run says goes under the button as well as to the application log: the log
        # window is where a user looks while a mesh takes its minutes, and where the reason a
        # run stopped is still to be read after the dialog about it has been closed.
        self.logic.logCallback = self.addLog

        # Make sure parameter node is initialized (needed for module reload)
        self.initializeParameterNode()

    def addLog(self, text: str, level: int = logging.INFO) -> None:
        """Append a message to the log window, warnings and errors in a colour of their own.

        One line per message and no blank line between them: each message is a sentence, ended
        with a full stop where whatever said it left one off, and that is what tells one from
        the next. The window is emptied once it grows past what is worth scrolling back
        through; a run that has said that much has said it to the application log too.
        """
        logTextEdit = self.ui.logTextEdit
        if len(logTextEdit.plainText) > 1024 * 256:
            logTextEdit.clear()
            logTextEdit.append(_("Log cleared."))
        text = " ".join(text.split())
        if text and text[-1] not in ".!?:":
            text += "."
        # Escaped by hand: what Qt offers for it wraps the text in a paragraph, and a paragraph
        # appended to a paragraph is set off from it by a blank line.
        escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if level >= logging.ERROR:
            escaped = '<span style="color: #d02020;">%s</span>' % escaped
        elif level >= logging.WARNING:
            escaped = '<span style="color: #d08000;">%s</span>' % escaped
        logTextEdit.append(escaped)
        logTextEdit.ensureCursorVisible()
        logTextEdit.repaint()

    def onReload(self) -> None:
        """Reload the module's own package before the module file, so that an edit to the
        pipeline is picked up by the Reload button as well as an edit to this file.

        Reloading the module file alone re-executes it, and the `from CfdMeshGeneratorLib ...`
        lines in it hand back the modules already imported. Each is re-executed in place first,
        in the order they import one another, so that what the module file then imports is
        what is on disk. A worker started after this runs from disk anyway.
        """
        import importlib

        import CfdMeshGeneratorLib
        from CfdMeshGeneratorLib import FTetWild, MeshingPipeline, MeshingWorker

        for module in (CfdMeshGeneratorLib, FTetWild, MeshingPipeline, MeshingWorker):
            logging.debug("Reloading %s", module.__name__)
            importlib.reload(module)
        ScriptedLoadableModuleWidget.onReload(self)

    def cleanup(self) -> None:
        """Called when the application closes and the module widget is destroyed."""
        self.removeObservers()
        # A meshing process left running would outlive the application.
        self.logic.cancel()

    def enter(self) -> None:
        """Called each time the user opens this module."""
        self.initializeParameterNode()

    def exit(self) -> None:
        """Called each time the user opens a different module."""
        if self._parameterNode:
            self._parameterNode.disconnectGui(self._parameterNodeGuiTag)
            self._parameterNodeGuiTag = None
            self.removeObserver(self._parameterNode, vtk.vtkCommand.ModifiedEvent, self._onParameterNodeModified)

    def onSceneStartClose(self, caller, event) -> None:
        """Called just before the scene is closed."""
        self.setParameterNode(None)

    def onSceneEndClose(self, caller, event) -> None:
        """Called just after the scene is closed."""
        if self.parent.isEntered:
            self.initializeParameterNode()

    def initializeParameterNode(self) -> None:
        """Ensure parameter node exists and observed."""
        self.setParameterNode(self.logic.getParameterNode())

        # Select the first surface in the scene if nothing is selected yet, to save a few clicks.
        # Not simply the first model node: a scene holds model nodes of Slicer's own - the slice
        # view planes among them - which are hidden from the selectors, so picking one would set
        # the module to a surface the user cannot see chosen and cannot choose again.
        if not self._parameterNode.inputSurface:
            for index in range(slicer.mrmlScene.GetNumberOfNodesByClass("vtkMRMLModelNode")):
                modelNode = slicer.mrmlScene.GetNthNodeByClass(index, "vtkMRMLModelNode")
                if modelNode.GetHideFromEditors() or not modelNode.GetPolyData():
                    continue
                self._parameterNode.inputSurface = modelNode
                break

    def setParameterNode(self, inputParameterNode: CfdMeshGeneratorParameterNode | None) -> None:
        """Set and observe the parameter node, so that the GUI follows it."""
        if self._parameterNode:
            self._parameterNode.disconnectGui(self._parameterNodeGuiTag)
            self.removeObserver(self._parameterNode, vtk.vtkCommand.ModifiedEvent, self._onParameterNodeModified)
        self._parameterNode = inputParameterNode
        if self._parameterNode:
            # Note: in the .ui file, a Qt dynamic property called "SlicerParameterName" is set on
            # each ui element that needs connection.
            self._parameterNodeGuiTag = self._parameterNode.connectGui(self.ui)
            # After connecting, not once at setup: connecting is what fills the combo box, and it
            # fills it afresh each time.
            self._updateMesherChoices()
            self.addObserver(self._parameterNode, vtk.vtkCommand.ModifiedEvent, self._onParameterNodeModified)
            self._onParameterNodeModified()

    def _onParameterNodeModified(self, caller=None, event=None) -> None:
        self._followInputSurface()
        self._updateApplyButton()
        self._updateEnabledStates()
        self._updateVisibilityButtons()

    def displayNodeOf(self, nodeName):
        """The display node of one of the module's own model nodes, made if the node has none.

        A node picked from a selector need not have one yet - an output node is created empty -
        and it is the press of a button that says the node is about to be looked at.
        """
        node = getattr(self._parameterNode, nodeName) if self._parameterNode else None
        if not node:
            return None
        if not node.GetDisplayNode():
            node.CreateDefaultDisplayNodes()
        return node.GetDisplayNode()

    def _updateVisibilityButtons(self) -> None:
        """Offer each pair of buttons only while there is a node for them to act on.

        On the node being there, and not on what is in it or how it is being shown: those change
        without the parameter node changing, and nothing here would hear of it, so a button that
        went by them could be greyed out over a surface that is on screen. What state the node is
        in is not asked either - the buttons say nothing about it, so there is nothing about them
        to keep in step.
        """
        for visibilityButton, edgesButton, nodeName in self.visibilityButtons:
            hasNode = (getattr(self._parameterNode, nodeName) if self._parameterNode else None) is not None
            visibilityButton.enabled = hasNode
            edgesButton.enabled = hasNode
        self.ui.outputMeshClipButton.enabled = (
            self._parameterNode is not None and self._parameterNode.outputMesh is not None)

    def onToggleVisibility(self, nodeName) -> None:
        displayNode = self.displayNodeOf(nodeName)
        if displayNode:
            displayNode.SetVisibility(not displayNode.GetVisibility())

    def onToggleEdgeVisibility(self, nodeName) -> None:
        displayNode = self.displayNodeOf(nodeName)
        if displayNode:
            displayNode.SetEdgeVisibility(not displayNode.GetEdgeVisibility())

    def onToggleClipping(self) -> None:
        """Cut the volume mesh open, and once it is cut, turn the cutting off and on.

        The first press has to make the thing that does the cutting, and where to put it is a
        guess; every press after that is about a box the user has since moved to where they
        wanted it, so it turns the clipping off rather than putting the box back.
        """
        displayNode = self.displayNodeOf("outputMesh")
        if not displayNode:
            return
        if displayNode.GetClipNode():
            displayNode.SetClipping(not displayNode.GetClipping())
            return
        self.logic.clipWithABoxThroughTheMiddle(self._parameterNode.outputMesh)

    def _followInputSurface(self) -> None:
        """Take what the outputs are called, and the array the faces are told apart by, from the
        surface that was picked.

        The array matters more than it looks: it is what holds the wall and the caps apart while
        the surface is remeshed, and a surface that arrives already labelled carries its labels
        under a name of its own. Left pointing at names the input does not use, the pipeline
        would renumber every cell of it into one face and the remesher would then be free to
        smooth the rim between a cap and the wall away. The usual names are offered by default,
        so a surface from Clip Vessel or SimVascular is found labelled as it is; one labelled
        under some other name, and only one, has that name put first.
        """
        surfaceNode = self._parameterNode.inputSurface if self._parameterNode else None
        surfaceNodeId = surfaceNode.GetID() if surfaceNode else None
        justPicked = surfaceNodeId != self._followedInputSurfaceId
        if justPicked:
            self._followedInputSurfaceId = surfaceNodeId
            # A node is often picked before it holds anything - the module picks the first model
            # in the scene when it opens, and a surface is written into a node that was made for
            # it - and there is nothing to read the name of a face ids array from until it does.
            if self._observedInputSurfaceNode:
                self.removeObserver(self._observedInputSurfaceNode,
                                    vtkMRMLModelNode.MeshModifiedEvent, self._onParameterNodeModified)
            self._observedInputSurfaceNode = surfaceNode
            if surfaceNode:
                self.addObserver(surfaceNode, vtkMRMLModelNode.MeshModifiedEvent,
                                 self._onParameterNodeModified)

        if not surfaceNode:
            return

        if justPicked:
            # The name a new output node gets when one is created from the selector.
            self.ui.outputMeshSelector.baseName = _("{name} volumetric").format(
                name=surfaceNode.GetName())
            self.ui.outputRemeshedSurfaceSelector.baseName = _("{name} remeshed").format(
                name=surfaceNode.GetName())

        surface = surfaceNode.GetPolyData()
        if surface is None:
            return
        names = MeshingPipeline.splitArrayNames(self._parameterNode.cellEntityIdsArrayNames)
        if any(surface.GetCellData().GetArray(name) is not None for name in names):
            return
        candidates = self.faceIdsArrayNames(surface)
        if len(candidates) == 1:
            logging.info("Reading the faces of %s from its %s array.",
                         surfaceNode.GetName(), candidates[0])
            self._parameterNode.cellEntityIdsArrayNames = ", ".join([candidates[0]] + names)
        elif candidates and justPicked:
            logging.warning("%s carries more than one array its faces could be read from (%s) "
                            "and none of the names offered (%s); leaving the face ids array "
                            "names as they are.",
                            surfaceNode.GetName(), ", ".join(candidates), ", ".join(names))

    @staticmethod
    def faceIdsArrayNames(surface):
        """The names of the cell arrays the surface could be labelling its faces by: one integer
        per cell, which is what a face id is."""
        integerTypes = (vtk.VTK_ID_TYPE, vtk.VTK_INT, vtk.VTK_UNSIGNED_INT, vtk.VTK_SHORT,
                        vtk.VTK_UNSIGNED_SHORT, vtk.VTK_LONG, vtk.VTK_UNSIGNED_LONG,
                        vtk.VTK_LONG_LONG, vtk.VTK_UNSIGNED_LONG_LONG, vtk.VTK_CHAR,
                        vtk.VTK_SIGNED_CHAR, vtk.VTK_UNSIGNED_CHAR)
        cellData = surface.GetCellData()
        arrays = [cellData.GetArray(index) for index in range(cellData.GetNumberOfArrays())]
        return [array.GetName() for array in arrays
                if array.GetName() and array.GetNumberOfComponents() == 1
                and array.GetDataType() in integerTypes]

    def _updateApplyButton(self, running=None) -> None:
        """Make the one button say what pressing it would do: start a run, or stop the one that
        is going.

        :param running: whether a run is in progress, where the logic cannot yet say - it is
          asked to start one only after the button has been turned round.
        """
        if running is None:
            running = self.logic.isRunning
        if running:
            self.ui.applyButton.text = _("Cancel")
            self.ui.applyButton.toolTip = _("Stop generating the mesh")
            self.ui.applyButton.enabled = True
            return
        self.ui.applyButton.text = _("Apply")
        # The output node is not asked for: left at "(Create New)" one is made on Apply (see
        # onApplyButton). Only the input has to be picked, there being nothing to mesh without it.
        if self._parameterNode and self._parameterNode.inputSurface:
            self.ui.applyButton.toolTip = _("Generate the volume mesh")
            self.ui.applyButton.enabled = True
        else:
            self.ui.applyButton.toolTip = _("Select an input surface")
            self.ui.applyButton.enabled = False

    def _updateMesherChoices(self) -> None:
        """Offer a mesher only where it can be run.

        TetGen's licence makes building it a decision, and an installation built without it has
        no TetGen to offer; saying so in the list it would have been chosen from is more use than
        letting it be chosen and refusing afterwards.
        """
        available = self.logic.availableMeshers()
        for index, mesher in enumerate(Mesher):
            if mesher in available:
                continue
            # The role a combo box keeps an item's flags under. Cleared, the item is shown but
            # cannot be picked.
            self.ui.mesherComboBox.setItemData(index, 0, qt.Qt.UserRole - 1)
            self.ui.mesherComboBox.setItemData(
                index, _("This installation was built without it"), qt.Qt.ToolTipRole)
        if self._parameterNode and self._parameterNode.mesher not in available and available:
            self._parameterNode.mesher = available[0]

    def _updateEnabledStates(self) -> None:
        """Grey out the parameters that the current choices leave without an effect."""
        if not self._parameterNode:
            return

        # What only fTetWild reads: TetGen keeps the surface it is given rather than staying
        # within a tolerance of it, and stops when its own quality bounds are met.
        usingFTetWild = self._parameterNode.mesher == Mesher.FTETWILD
        for widget in (self.ui.surfaceToleranceLabel, self.ui.surfaceToleranceSpinBox,
                       self.ui.stopEnergyLabel, self.ui.stopEnergySpinBox,
                       self.ui.maxOptimizationPassesLabel, self.ui.maxOptimizationPassesSpinBox,
                       self.ui.coarsenLabel, self.ui.coarsenCheckBox):
            widget.enabled = usingFTetWild

        # A constant edge length is one number, so neither the array nor its factor is read.
        fromArray = self._parameterNode.elementSizeMode == ElementSizeMode.EDGE_LENGTH_ARRAY
        self.ui.targetEdgeLengthArrayNameLabel.enabled = fromArray
        self.ui.targetEdgeLengthArrayNameLineEdit.enabled = fromArray
        self.ui.targetEdgeLengthFactorLabel.enabled = fromArray
        self.ui.targetEdgeLengthFactorSpinBox.enabled = fromArray

        remeshing = self._parameterNode.remeshSurface
        self.ui.remeshWallLabel.enabled = remeshing
        self.ui.remeshWallCheckBox.enabled = remeshing

        capping = self._parameterNode.capSurface
        self.ui.cappingMethodLabel.enabled = capping
        self.ui.cappingMethodComboBox.enabled = capping

        boundaryLayer = self._parameterNode.boundaryLayer
        for widget in (self.ui.boundaryLayerOnCapsLabel, self.ui.boundaryLayerOnCapsCheckBox,
                       self.ui.numberOfSubLayersLabel, self.ui.numberOfSubLayersSpinBox,
                       self.ui.subLayerRatioLabel, self.ui.subLayerRatioSpinBox,
                       self.ui.boundaryLayerThicknessFactorLabel, self.ui.boundaryLayerThicknessFactorSpinBox,
                       self.ui.numberOfSubstepsLabel, self.ui.numberOfSubstepsSpinBox,
                       self.ui.relaxationLabel, self.ui.relaxationSpinBox,
                       self.ui.localCorrectionFactorLabel, self.ui.localCorrectionFactorSpinBox):
            widget.enabled = boundaryLayer
        # The caps are only remeshed on their own when the boundary layer stops short of them.
        endcaps = boundaryLayer and not self._parameterNode.boundaryLayerOnCaps
        self.ui.endcapsEdgeLengthFactorLabel.enabled = endcaps
        self.ui.endcapsEdgeLengthFactorSpinBox.enabled = endcaps

    def onApplyButton(self) -> None:
        """Run processing when user clicks "Apply" button - or stop it, when the button says
        Cancel: the run is in a process of its own, and the event loop keeps turning while it
        goes, so the same button is there to be pressed again."""
        if self.logic.isRunning:
            self.logic.cancel()
            return
        # Once more before running: a node is often picked before it holds a surface, and until it
        # does there is nothing to read the name of its face ids array from.
        self._followInputSurface()
        # Nowhere to put the mesh yet, so make somewhere. Through the selector rather than the
        # scene, so that the node is made the way its "Create new" entry makes one - the same node
        # type and the same baseName, which _followInputSurface has already named after the input -
        # and comes back selected, so a second press writes to it rather than making another.
        if self._parameterNode.outputMesh is None:
            self.ui.outputMeshSelector.addNode()
        if self._parameterNode.mesher == Mesher.FTETWILD and not self.logic.isFTetWildAvailable():
            if not self.offerToInstallFTetWild():
                return
        self.ui.logTextEdit.plainText = ""
        try:
            self._updateApplyButton(running=True)
            # No wait cursor: the run is in another process and the application is not busy, so
            # the cursor should not say it is - and the Cancel button is there to be pressed.
            with slicer.util.tryWithErrorDisplay(_("Failed to generate the mesh.")):
                try:
                    self.logic.process(self._parameterNode)
                except MeshingCancelledError:
                    # What was asked for, so nothing to put a dialog up about.
                    self.logic.say(_("Meshing cancelled."))
                except Exception as error:
                    # Into the log window too, where it can still be read once the dialog
                    # about it has been closed.
                    self.logic.say(str(error), logging.ERROR)
                    raise
        finally:
            self._updateApplyButton(running=False)
            # The outputs have their display nodes now, so their buttons have something to act on.
            # In a finally, because a run that stopped half way still wrote what it had.
            self._updateVisibilityButtons()

    def offerToInstallFTetWild(self) -> bool:
        """Ask to download fTetWild, and say whether it can be used afterwards.

        Asking rather than simply doing it: this reaches out to the network and installs software
        into the application - or, on a Mac whose Slicer cannot host it, a Python of its own
        beside it - which is not something a press of Apply should be taken to mean.
        """
        if not slicer.util.confirmOkCancelDisplay(self.logic.describeFTetWildInstallation()):
            return False
        with slicer.util.tryWithErrorDisplay(_("Failed to install fTetWild."), waitCursor=True):
            self.logic.installFTetWild()
        return self.logic.isFTetWildAvailable()


#
# CfdMeshGeneratorLogic
#


class CfdMeshGeneratorLogic(ScriptedLoadableModuleLogic, MeshingPipeline):
    """The meshing pipeline in the application: what runs it, where, and what becomes of the
    result.

    The pipeline itself is MeshingPipeline, inherited whole, so that any step of it can be run in
    this process by a script or a test. process() - what Apply runs - does not run it here: it
    hands the surface to MeshingWorker in a PythonSlicer of its own, so that the run can be
    cancelled, and so that a mesher that crashes takes that process rather than the application.

    Uses ScriptedLoadableModuleLogic base class, available at:
    https://github.com/Slicer/Slicer/blob/main/Base/Python/slicer/ScriptedLoadableModule.py
    """

    # Whether fTetWild is to be run in a Python environment of its own rather than in Slicer's
    # Python. None asks FTetWild.needsSeparateEnvironment(), which says so only on a Mac running
    # an Intel build on an Apple silicon processor; a test sets it to walk that path elsewhere.
    separateFTetWildEnvironment = None

    def __init__(self) -> None:
        ScriptedLoadableModuleLogic.__init__(self)
        MeshingPipeline.__init__(self)
        self.fTetWildPython = self.fTetWildInterpreter()
        self.stepCallback = self.showStep
        # Called with (text, logging level) for everything a run says - each step, what the
        # pipeline warns about, how it ended - for whoever is showing it to the user. The
        # application log gets it regardless.
        self.logCallback = None
        # The worker process while one is running, and whether it was asked to stop.
        self._worker = None
        self._cancelled = False

    def getParameterNode(self):
        return CfdMeshGeneratorParameterNode(super().getParameterNode())

    def say(self, text, level=logging.INFO):
        """Tell the user something about the run: the log window, if there is one, and the
        application log.

        The application log is written here rather than by the caller, so that a line from the
        worker - which logged it there already, in its own process - arrives in this process's
        log exactly once, at the level it had.
        """
        logging.log(level, text)
        self.show(text, level)

    def show(self, text, level=logging.INFO):
        """Put a message in front of the user without logging it - for what has been logged
        already, by the pipeline here or in the worker."""
        if self.logCallback:
            self.logCallback(text, level)
        slicer.app.processEvents()

    def showStep(self, message):
        """Say which step is running where a user looks for it: the log window is the only
        sign of progress a long meshing run gives. The pipeline logs the step itself."""
        self._stepName = message
        self.show(message)

    #
    # Where fTetWild is run, and how it gets there.
    #

    @classmethod
    def fTetWildInterpreter(cls):
        """The Python fTetWild is run in, or None for this one. See FTetWild."""
        explicit = os.environ.get(FTetWild.PYTHON_ENVIRONMENT_VARIABLE)
        if explicit:
            return explicit
        separate = cls.separateFTetWildEnvironment
        if separate is None:
            separate = FTetWild.needsSeparateEnvironment()
        if not separate:
            return None
        return FTetWild.environmentPython(cls.fTetWildEnvironmentDirectory())

    @staticmethod
    def fTetWildEnvironmentDirectory():
        """Where the Python environment made for fTetWild lives: with the user's settings, which
        is where Slicer keeps what it downloads for a user."""
        return os.path.join(os.path.dirname(slicer.app.slicerUserSettingsFilePath),
                            "CfdMeshGenerator", "fTetWild")

    def describeFTetWildInstallation(self):
        """What installFTetWild() would do on this machine, for a dialog to ask about."""
        if self.fTetWildPython is None:
            return _(
                "fTetWild is not installed. It comes as the Python package {requirement}, under "
                "the Mozilla Public License 2.0, which can be downloaded and installed now. This "
                "needs an internet connection and takes a moment; it is only done once."
            ).format(requirement=FTETWILD_REQUIREMENT)
        if os.environ.get(FTetWild.PYTHON_ENVIRONMENT_VARIABLE):
            return _(
                "fTetWild is not installed in {python}, which the {variable} environment "
                "variable names as the Python to run it in. Install {requirement} there."
            ).format(python=self.fTetWildPython, variable=FTetWild.PYTHON_ENVIRONMENT_VARIABLE,
                     requirement=FTETWILD_REQUIREMENT)
        systemPython = FTetWild.findSystemPython()
        if systemPython:
            how = _("a virtual environment is made on the arm64 Python at {python}, and "
                    "fTetWild is installed into it").format(python=systemPython)
        else:
            how = _("no Python new enough for it was found on this Mac, so uv is installed "
                    "into Slicer's Python and fetches an arm64 CPython {version} to make a "
                    "virtual environment on, a hundred or so megabytes in all").format(
                version=FTetWild.PYTHON_VERSION)
        return _(
            "fTetWild is not installed. It comes as the Python package {requirement}, under the "
            "Mozilla Public License 2.0, and this Slicer cannot host it: it is an Intel build "
            "running on an Apple silicon processor, and the package is only made for the "
            "processor itself. A Python environment of its own can be made for it now, under "
            "{directory}: {how}. This needs an internet connection and a few minutes; it is "
            "only done once."
        ).format(requirement=FTETWILD_REQUIREMENT, directory=self.fTetWildEnvironmentDirectory(),
                 how=how)

    def installFTetWild(self):
        """Install fTetWild where this installation runs it. Reaches out to the network.

        Where that is a Python environment of its own, it is made the way SDFStent makes one:
        a venv on the machine's own arm64 Python, run as arm64. uv is the fallback for a Mac
        whose Pythons are all too old for pytetwild. Whatever was there before is removed
        first - this is only reached when fTetWild could not be run, so what was there was
        not working, which is what SDFStent does with a venv that will not start as arm64.
        """
        if self.fTetWildPython is None:
            slicer.util.pip_install(FTETWILD_REQUIREMENT)
        elif os.environ.get(FTetWild.PYTHON_ENVIRONMENT_VARIABLE):
            raise RuntimeError(self.describeFTetWildInstallation())
        else:
            directory = self.fTetWildEnvironmentDirectory()
            if os.path.isdir(directory):
                logging.info("Removing the Python environment at %s, which could not run "
                             "fTetWild, to make it afresh", directory)
                shutil.rmtree(directory, ignore_errors=True)
            os.makedirs(directory, exist_ok=True)
            systemPython = FTetWild.findSystemPython()
            if systemPython:
                logging.info("Making a Python environment for fTetWild under %s on %s",
                             directory, systemPython)
                commands = FTetWild.venvCommands(directory, systemPython)
            else:
                logging.info("No Python on this machine can host fTetWild; making a Python "
                             "environment for it under %s with uv", directory)
                try:
                    import uv
                except ImportError:
                    slicer.util.pip_install("uv")
                    import uv
                commands = FTetWild.uvCommands(directory, uv.find_uv_bin())
            for command, environment in commands:
                self.say(_("Running: {command}").format(command=" ".join(command)))
                process = slicer.util.launchConsoleProcess(command, updateEnvironment=environment)
                slicer.util.logProcessOutput(
                    process, logCallback=lambda line: self.logCallback and self.logCallback(line))
        if not self.isFTetWildAvailable():
            raise RuntimeError(_("fTetWild was installed, but still cannot be run."))

    #
    # Running the pipeline in a process of its own.
    #

    @property
    def isRunning(self):
        """Whether a meshing process is going right now."""
        return self._worker is not None and self._worker.poll() is None

    def process(self, parameters: CfdMeshGeneratorParameterNode) -> None:
        """Mesh the input surface of the given parameter node into its output nodes.

        In a process of its own (see generateMeshInSeparateProcess), which is what makes it
        possible to stop: cancel() kills the process, and this then raises
        MeshingCancelledError. The event loop is kept turning meanwhile, so the button that
        started the run can be pressed to stop it.
        """
        if not parameters.inputSurface:
            raise ValueError(_("No input surface"))
        if not parameters.inputSurface.GetPolyData():
            raise ValueError(_("The input model holds no surface. A model holding a volume mesh "
                               "is already meshed; this module takes the surface that bounds one."))
        if not parameters.outputMesh:
            raise ValueError(_("No output mesh node"))
        if self.isRunning:
            raise RuntimeError(_("A mesh is already being generated."))

        startTime = time.time()

        arguments = self.meshingArguments(parameters)
        cellEntityIdsArrayName = arguments["cellEntityIdsArrayName"]
        mesh, remeshedSurface = self.generateMeshInSeparateProcess(
            parameters.inputSurface.GetPolyData(), **arguments)

        parameters.outputMesh.SetAndObserveMesh(mesh)
        if self.showMeshInScene(parameters.outputMesh, cellEntityIdsArrayName, showEdges=True):
            # The mesh was made from the input surface, so it stands exactly where the surface
            # does and is hidden behind it. Only the first time it is shown: after that the
            # surface is visible because it was turned back on, and a run at another edge length
            # is no reason to undo that.
            self.hideNode(parameters.inputSurface)
        if parameters.outputRemeshedSurface:
            parameters.outputRemeshedSurface.SetAndObserveMesh(remeshedSurface)
            self.showMeshInScene(parameters.outputRemeshedSurface, cellEntityIdsArrayName)

        self.say(_("Meshing completed in {seconds:.1f} seconds: {cells} cells, {points} points.")
                 .format(seconds=time.time() - startTime, cells=mesh.GetNumberOfCells(),
                         points=mesh.GetNumberOfPoints()))

        # Said out loud rather than left in the log: what comes back is a hollow shell that looks
        # like a mesh until it is opened, and a solver would not accept it.
        if self.lastTetrahedralizationFailed:
            mesherName = parameters.mesher.label()
            if parameters.boundaryLayer:
                raise RuntimeError(_(
                    "{mesher} could not fill the space left inside the boundary layer, so the "
                    "output holds the layer and the surface but no tetrahedra. The layer has "
                    "most likely folded over itself, which it does first where a cap meets the "
                    "wall at a corner: turn \"Layer on caps\" off, make the layer thinner, or "
                    "give it more substeps to settle over.").format(mesher=mesherName))
            raise RuntimeError(_(
                "{mesher} could not fill the surface with tetrahedra, so the output holds only "
                "the surface. The surface it was given is not one it can fill: check that the "
                "input is closed and does not cross itself.").format(mesher=mesherName))

    @classmethod
    def meshingArguments(cls, parameters: CfdMeshGeneratorParameterNode) -> dict:
        """The arguments of generateMesh(), read off the parameter node. The face ids array is
        the one of those offered that the input surface carries; see
        chooseCellEntityIdsArrayName()."""
        surface = parameters.inputSurface.GetPolyData() if parameters.inputSurface else None
        return dict(
            targetEdgeLength=parameters.targetEdgeLength,
            targetEdgeLengthArrayName=parameters.targetEdgeLengthArrayName,
            targetEdgeLengthFactor=parameters.targetEdgeLengthFactor,
            triangleSplitFactor=parameters.triangleSplitFactor,
            endcapsEdgeLengthFactor=parameters.endcapsEdgeLengthFactor,
            maxEdgeLength=parameters.maxEdgeLength,
            minEdgeLength=parameters.minEdgeLength,
            cellEntityIdsArrayName=cls.chooseCellEntityIdsArrayName(
                surface, parameters.cellEntityIdsArrayNames),
            capIdsArrayName=parameters.capIdsArrayName.strip(),
            boundaryLabelsArrayName=parameters.boundaryLabelsArrayName,
            boundaryPointOrderArrayName=parameters.boundaryPointOrderArrayName,
            elementSizeMode=parameters.elementSizeMode.value,
            cappingMethod=parameters.cappingMethod.value,
            skipCapping=not parameters.capSurface,
            skipRemeshing=not parameters.remeshSurface,
            remeshCapsOnly=not parameters.remeshWall,
            mesher=parameters.mesher.value,
            volumeElementScaleFactor=parameters.volumeElementScaleFactor,
            surfaceTolerance=parameters.surfaceTolerance,
            stopEnergy=parameters.stopEnergy,
            maxOptimizationPasses=parameters.maxOptimizationPasses,
            coarsen=parameters.coarsen,
            boundaryLayer=parameters.boundaryLayer,
            boundaryLayerOnCaps=parameters.boundaryLayerOnCaps,
            numberOfSubLayers=parameters.numberOfSubLayers,
            subLayerRatio=parameters.subLayerRatio,
            boundaryLayerThicknessFactor=parameters.boundaryLayerThicknessFactor,
            numberOfSubsteps=parameters.numberOfSubsteps,
            relaxation=parameters.relaxation,
            localCorrectionFactor=parameters.localCorrectionFactor,
            tetrahedralize=parameters.tetrahedralize,
            carriedCellArrays=cls.splitArrayNames(parameters.carriedCellArrays))

    def generateMeshInSeparateProcess(self, surface, **arguments):
        """generateMesh(), run by MeshingWorker in a PythonSlicer of its own.

        The surface goes to the worker as a file and the mesh comes back as one, through a
        directory made for the run and removed after it. What the worker prints meanwhile is
        relayed to the log as it arrives, and the steps it announces to the status bar.

        :raises MeshingCancelledError: if cancel() was called before the worker finished.
        :raises RuntimeError: if the worker died without a result - which is what a mesher that
          crashed leaves behind - or if the pipeline raised; a ValueError it raised is raised
          again as one.
        """
        directory = slicer.util.tempDirectory("CfdMeshGenerator")
        try:
            inputPath = os.path.join(directory, "input.vtp")
            parametersPath = os.path.join(directory, "parameters.json")
            meshPath = os.path.join(directory, "mesh.vtu")
            surfacePath = os.path.join(directory, "surface.vtp")
            resultPath = os.path.join(directory, "result.json")
            MeshingWorker.write(inputPath, surface)
            with open(parametersPath, "w") as parametersFile:
                json.dump({"arguments": arguments, "fTetWildPython": self.fTetWildPython},
                          parametersFile)

            # -u: what the worker says is to arrive as it is said, not when a buffer fills.
            command = [self.pythonSlicerExecutable(), "-u", MeshingWorker.__file__,
                       "--input", inputPath, "--parameters", parametersPath,
                       "--output-mesh", meshPath, "--output-surface", surfacePath,
                       "--result", resultPath]
            returnCode, output = self.runWorker(command)

            if self._cancelled:
                raise MeshingCancelledError(_("Meshing was cancelled."))
            result = None
            if os.path.isfile(resultPath):
                with open(resultPath) as resultFile:
                    result = json.load(resultFile)
            if result is None:
                raise RuntimeError(_(
                    "The meshing process ended without a result (exit code {code}), which is "
                    "what a mesher that crashed on its input leaves behind. The end of what it "
                    "said:\n{output}").format(code=returnCode, output=output))
            if "error" in result:
                errorType = ValueError if result["error"]["type"] == "ValueError" else RuntimeError
                raise errorType(result["error"]["message"])
            self.lastTetrahedralizationFailed = bool(result.get("tetrahedralizationFailed"))
            return self.readMesh(meshPath), self.readSurface(surfacePath)
        finally:
            shutil.rmtree(directory, ignore_errors=True)

    @staticmethod
    def pythonSlicerExecutable():
        """The PythonSlicer this application runs its Python with, to run the worker in: the
        same interpreter, with the same packages and the same wrapped VMTK classes."""
        executable = sys.executable
        if "PythonSlicer" not in os.path.basename(executable):
            executable = shutil.which("PythonSlicer") or executable
        return executable

    def runWorker(self, command):
        """Run the worker and relay what it says until it ends, keeping the event loop turning.

        :return: (exit code, the last lines it printed, as one string)
        """
        environment = os.environ.copy()
        # The worker imports the wrapped VMTK classes and this module's own package from wherever
        # this process found them, which an extension built rather than installed passes to the
        # application on its command line and not in the environment.
        environment["PYTHONPATH"] = os.pathsep.join(
            [path for path in sys.path if path and os.path.isdir(path)]
            + [path for path in environment.get("PYTHONPATH", "").split(os.pathsep) if path])
        # VTK, built to report leaks, reports them at exit in a dialog on Windows, and a dialog in
        # a process with no window to show it in is a process that never exits. This is the
        # switch that has it write them to stderr instead, where they are relayed like the rest.
        environment["DASHBOARD_TEST_FROM_CTEST"] = "1"
        popenArguments = {}
        if os.name == "nt":
            startupInfo = subprocess.STARTUPINFO()
            startupInfo.dwFlags = subprocess.STARTF_USESHOWWINDOW
            startupInfo.wShowWindow = subprocess.SW_HIDE
            popenArguments["startupinfo"] = startupInfo
        else:
            # A process group of its own, so that cancel() can take the worker and any
            # interpreter it started for fTetWild down together.
            popenArguments["start_new_session"] = True

        self._cancelled = False
        self._worker = subprocess.Popen(
            command, env=environment, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            universal_newlines=True, **popenArguments)
        lines = queue.Queue()

        def readOutput():
            while True:
                try:
                    line = self._worker.stdout.readline()
                except UnicodeDecodeError:
                    continue
                if not line:
                    break
                lines.put(line.rstrip("\r\n"))
            lines.put(None)

        reader = threading.Thread(target=readOutput, daemon=True)
        reader.start()

        lastLines = collections.deque(maxlen=30)
        try:
            while True:
                try:
                    line = lines.get(timeout=0.05)
                except queue.Empty:
                    slicer.app.processEvents()
                    continue
                if line is None:
                    break
                lastLines.append(line)
                self.relayWorkerLine(line)
            returnCode = self._worker.wait()
        finally:
            self._worker = None
        return returnCode, "\n".join(lastLines)

    def relayWorkerLine(self, line):
        """Pass one line of the worker's output on: a step to the status bar and the log window,
        the rest to the logs at the level it was logged at there.

        A step is announced twice by the worker - once as a step, then as the INFO line its own
        logging writes - and only the step is shown, so that the window does not say everything
        twice; the INFO line goes to the application log alone.
        """
        if line.startswith(MeshingWorker.STEP_PREFIX):
            self.showStep(line[len(MeshingWorker.STEP_PREFIX):])
            return
        # The worker's own logging writes each line with its level in front; anything else -
        # what VTK prints, a traceback - arrives as it is.
        levelName, separator, message = line.partition(": ")
        level = {"DEBUG": logging.DEBUG, "INFO": logging.INFO, "WARNING": logging.WARNING,
                 "ERROR": logging.ERROR, "CRITICAL": logging.ERROR}.get(levelName)
        if level is None:
            level, message = logging.INFO, line
        logging.log(level, message)
        if level == logging.INFO and message == self._stepName:
            return
        self.show(message, level)

    def cancel(self) -> None:
        """Stop the run in progress, if there is one; process() then raises
        MeshingCancelledError. Nothing of the run is kept."""
        worker = self._worker
        if worker is None or worker.poll() is not None:
            return
        self._cancelled = True
        self.say(_("Stopping the meshing process."))
        if os.name == "nt":
            # The worker may have an interpreter of its own running fTetWild under it; /T takes
            # the whole tree, which terminate() would not.
            subprocess.run(["taskkill", "/F", "/T", "/PID", str(worker.pid)],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                           **FTetWild.hiddenWindowArguments())
        else:
            os.killpg(worker.pid, signal.SIGTERM)

    @staticmethod
    def readMesh(path):
        reader = vtk.vtkXMLUnstructuredGridReader()
        reader.SetFileName(path)
        reader.Update()
        mesh = vtk.vtkUnstructuredGrid()
        mesh.ShallowCopy(reader.GetOutput())
        return mesh

    @staticmethod
    def readSurface(path):
        surface = vtk.vtkPolyData()
        surface.ShallowCopy(MeshingWorker.readSurface(path))
        return surface

    #
    # What becomes of the result in the scene.
    #

    def clipWithABoxThroughTheMiddle(self, modelNode):
        """Clip the model to a box laid over the middle of it, and show the box.

        The box is the model's own bounding box, halved along the model's shortest side: a slab
        through the middle of a vessel mesh, which is what shows the elements inside it. It is a
        starting point rather than an answer - it is left visible, and thinly filled, so that it
        can be taken hold of and moved to wherever the cut is wanted.

        Whole elements are kept: an element the box crosses is either in or out, never cut
        through. A mesh sliced through its elements shows faces that are not element faces, and
        the reason for looking inside is to see the elements as they are.

        :return: the clip node now driving the model's display.
        """
        if not modelNode.GetDisplayNode():
            modelNode.CreateDefaultDisplayNodes()
        displayNode = modelNode.GetDisplayNode()
        if not displayNode:
            return None

        bounds = [0.0] * 6
        modelNode.GetRASBounds(bounds)
        size = [bounds[1] - bounds[0], bounds[3] - bounds[2], bounds[5] - bounds[4]]
        center = [(bounds[0] + bounds[1]) / 2.0, (bounds[2] + bounds[3]) / 2.0,
                  (bounds[4] + bounds[5]) / 2.0]
        size[size.index(min(size))] *= 0.5

        roiNode = slicer.mrmlScene.AddNewNodeByClass(
            "vtkMRMLMarkupsROINode", _("{name} clip box").format(name=modelNode.GetName()))
        roiNode.SetCenter(center)
        roiNode.SetSize(size)
        roiNode.CreateDefaultDisplayNodes()
        roiDisplayNode = roiNode.GetDisplayNode()
        if roiDisplayNode:
            # Enough fill to see which way round the box lies, little enough to see the mesh
            # through it.
            roiDisplayNode.SetFillVisibility(True)
            roiDisplayNode.SetFillOpacity(0.05)
            roiDisplayNode.SetVisibility(True)

        clipNode = slicer.mrmlScene.AddNewNodeByClass(
            "vtkMRMLClipNode", _("{name} clip").format(name=modelNode.GetName()))
        clipNode.SetClippingMethod(slicer.vtkMRMLClipNode.WholeCells)
        clipNode.AddAndObserveClippingNodeID(roiNode.GetID())
        clipNode.SetClippingNodeState(roiNode, slicer.vtkMRMLClipNode.ClipNegativeSpace)

        displayNode.SetAndObserveClipNodeID(clipNode.GetID())
        displayNode.SetClipping(True)
        return clipNode

    displaySetUpAttributeName = "CfdMeshGenerator.DisplaySetUp"

    @staticmethod
    def hideNode(modelNode):
        """Take a node out of the views, if it is in them and has a display to take out."""
        displayNode = modelNode.GetDisplayNode() if modelNode else None
        if displayNode:
            displayNode.SetVisibility(False)

    def showMeshInScene(self, modelNode, cellEntityIdsArrayName, showEdges=False):
        """Show the mesh, coloured by the face each of its cells belongs to.

        Once per node: a node that has been shown before carries whatever has been made of it
        since - a colour, a scalar array, its visibility, an opacity chosen to see inside it, its
        edges turned off - and rerunning Apply to try another edge length is no reason to undo any
        of that.

        :param showEdges: whether to draw the element edges. What there is to look at in a volume
          mesh is the elements, and a surface shaded without them says nothing about how finely it
          was meshed or how good its elements are - which is the first thing to want to know of a
          mesh that has just been made. The edges button beside the selector turns them off again.
        :return: whether the display was set up here, which is to say whether this is the first
          time the node has been shown. A caller with something else to arrange around that -
          getting whatever was in the way out of it - can then do it once rather than on every run.
        """
        if modelNode.GetAttribute(self.displaySetUpAttributeName) == "true":
            return False
        modelNode.SetAttribute(self.displaySetUpAttributeName, "true")

        if not modelNode.GetDisplayNode():
            modelNode.CreateDefaultDisplayNodes()
        displayNode = modelNode.GetDisplayNode()
        if not displayNode:
            return False
        mesh = modelNode.GetMesh()
        if mesh and mesh.GetCellData().GetArray(cellEntityIdsArrayName):
            displayNode.SetActiveScalar(cellEntityIdsArrayName, vtk.vtkAssignAttribute.CELL_DATA)
            # Over the ids the mesh actually carries, and through a table that is opaque
            # throughout. A discrete label table would read the ids as the label numbers they are,
            # but the entry it gives label 0 is transparent - and 0 is what every cell of a mesh
            # whose faces were never told apart carries, so the whole thing would come up
            # invisible, which is no way to hand back an hour of meshing.
            displayNode.SetAndObserveColorNodeID("vtkMRMLColorTableNodeRainbow")
            displayNode.SetScalarRangeFlag(slicer.vtkMRMLDisplayNode.UseDataScalarRange)
            displayNode.SetScalarVisibility(True)
        else:
            displayNode.SetScalarVisibility(False)
        displayNode.SetEdgeVisibility(showEdges)
        displayNode.SetVisibility(True)
        return True


#
# CfdMeshGeneratorTest
#


class CfdMeshGeneratorTest(ScriptedLoadableModuleTest):
    """A smoke test, for Reload and Test and for the ctest that runs this file.

    It drives the module the way a user does: a surface is put in the scene, the parameters go
    on the module's parameter node, the parameter node is shown in the GUI, and Apply is pressed
    - rather than the logic being called behind the widget's back. What the widget does around
    the pipeline is then part of what is tested: the output node it makes, the process it starts
    and reads back, the display it sets up, and a broken reference in the button handler.

    What it checks is that the pipeline runs end to end on the simplest surface there is.
    Everything else - each mesher in turn, the boundary layer, the face ids, cancelling, and a
    real vessel rather than a tube - is in Testing/Python, as separate files so that a failure
    names the behaviour that broke rather than the one long run it happened during, and so that
    they can be run one per process.

    Uses ScriptedLoadableModuleTest base class, available at:
    https://github.com/Slicer/Slicer/blob/main/Base/Python/slicer/ScriptedLoadableModule.py
    """

    def setUp(self):
        """Do whatever is needed to reset the state - typically a scene clear will be enough."""
        slicer.mrmlScene.Clear()

    def runTest(self):
        self.setUp()
        self.test_CfdMeshGenerator1()

    def moduleWidget(self):
        """The module's own widget, the one the application drives.

        Slicer builds it, parents it, gives it the scene and runs setup(), so this is the same
        object a user has in front of them. Selecting the module is what normally builds it, but
        that needs the module selector in the main window, which a test run started with
        --no-main-window has not got; getModuleWidget builds the representation on demand either
        way, so the selection is best effort.
        """
        try:
            slicer.util.selectModule("CfdMeshGenerator")
        except RuntimeError:
            pass
        return slicer.util.getModuleWidget("CfdMeshGenerator")

    def test_CfdMeshGenerator1(self):
        """An open tube must come back as a volume mesh: capped, filled with tetrahedra, and with
        the wall and each of the two caps under an id of its own, so that a boundary condition can
        be assigned to each of them.

        TetGen only. fTetWild is a download, and a smoke test is not the place to reach for the
        network; Testing/Python puts every behaviour to both.
        """
        self.delayDisplay("Starting the test")

        widget = self.moduleWidget()
        if not widget.logic.isTetGenAvailable():
            self.delayDisplay("Skipped: this installation was built without TetGen")
            return

        inputSurfaceNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLModelNode", "tube")
        inputSurfaceNode.SetAndObserveMesh(self.openTube())
        inputSurfaceNode.CreateDefaultDisplayNodes()

        # Everything the user would set, put on the parameter node rather than into the widgets:
        # the parameter node is what the module reads, and what a saved scene restores. The
        # output is left at "(Create New)", which is how a user leaves it: Apply makes the node.
        parameterNode = widget.logic.getParameterNode()
        parameterNode.inputSurface = inputSurfaceNode
        parameterNode.outputMesh = None
        # Coarser than this and TetGen is handed a surface it cannot fill.
        parameterNode.targetEdgeLength = 0.4
        parameterNode.mesher = Mesher.TETGEN
        parameterNode.boundaryLayer = False

        # ...and then shown in the GUI. From here on the widget is driven by its own button.
        widget.setParameterNode(parameterNode)
        self.assertIs(widget.ui.inputSurfaceSelector.currentNode(), inputSurfaceNode,
                      "the input surface did not reach the GUI")
        self.assertTrue(widget.ui.applyButton.enabled, "Apply is not offered with an input picked")

        self.delayDisplay("Applying")
        widget.onApplyButton()

        outputMeshNode = parameterNode.outputMesh
        self.assertIsNotNone(outputMeshNode, "Apply made no node to write the mesh into")
        self.assertIn("tube", outputMeshNode.GetName(), "the output is not named after the input")
        mesh = outputMeshNode.GetMesh()
        self.assertIsNotNone(mesh, "the output node holds no mesh")
        cellTypes = vtk.vtkCellTypes()
        mesh.GetCellTypes(cellTypes)
        self.assertTrue(cellTypes.IsType(vtk.VTK_TETRA), "the mesh holds no tetrahedra")
        # 0 for the tetrahedra, 1 for the wall, and one id per cap above it, under the first of
        # the default names, the tube arriving unlabelled.
        ids = mesh.GetCellData().GetArray("CellEntityIds")
        self.assertIsNotNone(ids, "the mesh carries no face ids")
        self.assertEqual(
            set(int(ids.GetTuple1(index)) for index in range(ids.GetNumberOfTuples())),
            {0, 1, 2, 3})
        self.assertFalse(widget.logic.lastTetrahedralizationFailed)
        self.assertFalse(widget.logic.isRunning)

        # What a user sees afterwards: the mesh with its elements drawn, coloured by face, and
        # the surface it was made from out of its way.
        displayNode = outputMeshNode.GetDisplayNode()
        self.assertIsNotNone(displayNode, "the mesh was given no display")
        self.assertTrue(displayNode.GetVisibility())
        self.assertTrue(displayNode.GetEdgeVisibility(), "the elements of the mesh are not drawn")
        self.assertTrue(displayNode.GetScalarVisibility(), "the faces are not coloured apart")
        self.assertFalse(inputSurfaceNode.GetDisplayNode().GetVisibility(),
                         "the input surface is still in front of the mesh")
        self.assertEqual(widget.ui.applyButton.text, "Apply", "the button still reads Cancel")

        self.delayDisplay("Test passed")

    @staticmethod
    def openTube(numberOfAxialPoints=12, numberOfCircumferentialPoints=24, height=10.0, radius=1.0):
        """A tube open at both ends, standing in for a clipped vessel."""
        import math
        points, polys = vtk.vtkPoints(), vtk.vtkCellArray()
        for axialIndex in range(numberOfAxialPoints):
            z = height * axialIndex / (numberOfAxialPoints - 1)
            for circumferentialIndex in range(numberOfCircumferentialPoints):
                angle = 2.0 * math.pi * circumferentialIndex / numberOfCircumferentialPoints
                points.InsertNextPoint(radius * math.cos(angle), radius * math.sin(angle), z)
        for axialIndex in range(numberOfAxialPoints - 1):
            for circumferentialIndex in range(numberOfCircumferentialPoints):
                nextIndex = (circumferentialIndex + 1) % numberOfCircumferentialPoints
                first = axialIndex * numberOfCircumferentialPoints + circumferentialIndex
                second = axialIndex * numberOfCircumferentialPoints + nextIndex
                third = (axialIndex + 1) * numberOfCircumferentialPoints + circumferentialIndex
                fourth = (axialIndex + 1) * numberOfCircumferentialPoints + nextIndex
                polys.InsertNextCell(3, [first, second, fourth])
                polys.InsertNextCell(3, [first, fourth, third])
        surface = vtk.vtkPolyData()
        surface.SetPoints(points)
        surface.SetPolys(polys)
        return surface
